apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-1
  namespace: demo-1
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'hello from PVC' > /data/test.txt && sleep 3600"]
    volumeMounts:
    - name: demo-vol-1
      mountPath: /data

