apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  namespace: demo-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem # default, other option is Block
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  claimRef:
    name: pvc-2
    namespace: demo-2
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-1  