apiVersion: v1
kind: Pod
metadata:
  name:
  namespace: demo
spec:
  nodeSelector:
    taint: demo
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Ready! && sleep 3600"]
      resources:
        requests:
          cpu: 50m
  tolerations:
  - key: "taint"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"