apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: restricted-ns
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false #true should fail
    volumeMounts:
      - name: test-vol
        mountPath: /hostdata
  volumes:
  - name: test-vol
    hostPath:
      path: /tmp